### ISSUE TITLE
toy dataset格式不对？

### ISSUE THREAD

**Issue by Jiangrijin** [weiyinwei/GRCN#1]
你好，我下载了MMGCN中提到的toy dataset，其中的user id和item id是分别编号的，但是我读代码时感觉代码的逻辑应该是item跟在user后面编号。
举个例子，我认为按照代码的逻辑编号应该是user: [1, 2, 3, 4, 5 ,..., n], item: [n+1,  n+2, ...]
不知道是否我理解有误？

**Comment by weiyinwei** [comment]
您好，您理解的没有问题，您可以对所有item id都增加num_user即可。

**Comment by Jiangrijin** [comment]
> 您好，您理解的没有问题，您可以对所有item id都增加num_user即可。

好的，非常感谢！
